In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
buy = pd.read_csv('buy.csv')
buy

나이  월수입 상품구매여부
0   26  160     구매
1   35  210    비구매
2   26  220   비구매 
3   29  260     구매
4   22  110    비구매
5   32  210    비구매
6   37  310     구매
7   21  110    비구매
8   28  210    비구매
9   31  260     구매
10  36  390     구매
11  23  110    비구매
12  32  340    비구매
13  29  170     구매
14  37  340     구매
15  31  240    비구매
16  27  230    비구매
17  23  210    비구매
18  40  440     구매
19  27  140    비구매

In [3]:
buy.columns = ['age','paycheck','purchase'] # age, paycheck : 연속, purchase : 범주
buy.head()

age  paycheck purchase
0   26       160       구매
1   35       210      비구매
2   26       220     비구매 
3   29       260       구매
4   22       110      비구매

In [4]:
buy.shape

(20, 3)

In [5]:
buy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   age       20 non-null     int64 
 1   paycheck  20 non-null     int64 
 2   purchase  20 non-null     object
dtypes: int64(2), object(1)
memory usage: 608.0+ bytes


In [6]:
x = buy.iloc[:,[0,1]]
y = buy.iloc[:,[2]]
x, y

(    age  paycheck
 0    26       160
 1    35       210
 2    26       220
 3    29       260
 4    22       110
 5    32       210
 6    37       310
 7    21       110
 8    28       210
 9    31       260
 10   36       390
 11   23       110
 12   32       340
 13   29       170
 14   37       340
 15   31       240
 16   27       230
 17   23       210
 18   40       440
 19   27       140,
    purchase
 0        구매
 1       비구매
 2      비구매 
 3        구매
 4       비구매
 5       비구매
 6        구매
 7       비구매
 8       비구매
 9        구매
 10       구매
 11      비구매
 12      비구매
 13       구매
 14       구매
 15      비구매
 16      비구매
 17      비구매
 18       구매
 19      비구매)

In [17]:
np.array(y).reshape(len(y),)

array(['구매', '비구매', '비구매 ', '구매', '비구매', '비구매', '구매', '비구매', '비구매', '구매',
       '구매', '비구매', '비구매', '구매', '구매', '비구매', '비구매', '비구매', '구매', '비구매'],
      dtype=object)

In [18]:
type(np.array(y).reshape(len(y),))

numpy.ndarray

In [8]:
# 데이터 정규화 -> StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x) # data 훈련

x = scaler.transform(x) # 변환
x

array([[-0.67743894, -0.81302375],
       [ 1.0161584 , -0.25994637],
       [-0.67743894, -0.14933089],
       [-0.11290649,  0.29313101],
       [-1.43014887, -1.36610113],
       [ 0.45162596, -0.25994637],
       [ 1.39251337,  0.84620839],
       [-1.61832635, -1.36610113],
       [-0.30108397, -0.25994637],
       [ 0.26344848,  0.29313101],
       [ 1.20433589,  1.7311322 ],
       [-1.24197138, -1.36610113],
       [ 0.45162596,  1.17805482],
       [-0.11290649, -0.70240827],
       [ 1.39251337,  1.17805482],
       [ 0.26344848,  0.07190006],
       [-0.48926145, -0.03871542],
       [-1.24197138, -0.25994637],
       [ 1.95704582,  2.28420958],
       [-0.48926145, -1.0342547 ]])

In [9]:
# knn 분류 모델 생성(범주형 데이터 분석)
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 2)
classifier.fit(x,y)

C:\Users\khb16\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=2)

In [10]:
# 원래의 데이터를 넣어서 예측
y_pred = classifier.predict(x)
y_pred

array(['구매', '비구매', '비구매', '구매', '비구매', '비구매', '구매', '비구매', '비구매', '구매',
       '구매', '비구매', '구매', '구매', '구매', '구매', '비구매', '비구매', '구매', '구매'],
      dtype=object)

In [11]:
y

purchase
0        구매
1       비구매
2      비구매 
3        구매
4       비구매
5       비구매
6        구매
7       비구매
8       비구매
9        구매
10       구매
11      비구매
12      비구매
13       구매
14       구매
15      비구매
16      비구매
17      비구매
18       구매
19      비구매

In [16]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y, y_pred)) # (실제값, 예측값) 비교
print(classification_report(y, y_pred))

[[8 0 0]
 [3 8 0]
 [0 1 0]]
              precision    recall  f1-score   support

          구매       0.73      1.00      0.84         8
         비구매       0.89      0.73      0.80        11
        비구매        0.00      0.00      0.00         1

    accuracy                           0.80        20
   macro avg       0.54      0.58      0.55        20
weighted avg       0.78      0.80      0.78        20



C:\Users\khb16\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\khb16\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\khb16\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
