In [22]:
from sklearn import datasets 
from sklearn import svm
from sklearn import metrics, accuary
import numpy as np
import pandas as pd

# 유방암 환자 데이터 로딩

cancer = datasets.load_breast_cancer()

ImportError: cannot import name 'accuary' from 'sklearn' (C:\Users\khb16\anaconda3\lib\site-packages\sklearn\__init__.py)

In [2]:
cancer.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [3]:
# 13개의 특징 정보(features)

print(cancer.feature_names)

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [4]:
# label type of cancer(악성 또는 양성)
print(cancer.target_names)

['malignant' 'benign']


In [15]:
from sklearn.model_selection import train_test_split

# 훈련용 데이터 : 테스트 데이터 분리(7:3)
x_train, x_test, y_train, y_test = train_test_split(cancer.data, cancer.target, test_size = 0.3, random_state=42)

In [ ]:
# 문제 1
# 위 데이터 기반, svm 모델을 만들어 보세요 
# 커널 함수는 선형으로 사용 
# 모델 이름 : clf

In [16]:
# 모델 생성
clf = svm.SVC(kernel = 'linear')

In [17]:
# 모델 훈련
clf.fit(x_train, y_train) # input train data

SVC(kernel='linear')

In [19]:
# 문제 2
# 모델 훈련 했나요? 예측해 보세요
y_pred = clf.predict(x_test)
y_pred
# 예측값 도출

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1])

In [24]:
# 모델의 정확도

print(metrics.accuracy_score(y_test, y_pred))
# 모델 정확도는 96%

0.9649122807017544


In [26]:
print(metrics.confusion_matrix(y_test, y_pred))
print()
print(metrics.classification_report(y_test, y_pred))

[[ 59   4]
 [  2 106]]

              precision    recall  f1-score   support

           0       0.97      0.94      0.95        63
           1       0.96      0.98      0.97       108

    accuracy                           0.96       171
   macro avg       0.97      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171

